remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



title: Keissen's homepage
tagline: Offering documentation on my assets, and various customization guides.
description: VRC asset documentation and customization guides. Nothing to see here, still testing.
google_analytics: G-WCEF3XGBVM